package keystrokesmod.module;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import keystrokesmod.Raven;
import keystrokesmod.module.Module;
import keystrokesmod.module.impl.client.ChatCommands;
import keystrokesmod.module.impl.client.CommandLine;
import keystrokesmod.module.impl.client.Gui;
import keystrokesmod.module.impl.client.Relationships;
import keystrokesmod.module.impl.client.Settings;
import keystrokesmod.module.impl.combat.AimAssist;
import keystrokesmod.module.impl.combat.AntiKnockback;
import keystrokesmod.module.impl.combat.AutoClicker;
import keystrokesmod.module.impl.combat.AutoWeapon;
import keystrokesmod.module.impl.combat.Autoblock;
import keystrokesmod.module.impl.combat.ClickAssist;
import keystrokesmod.module.impl.combat.HitBox;
import keystrokesmod.module.impl.combat.HitSelect;
import keystrokesmod.module.impl.combat.JumpReset;
import keystrokesmod.module.impl.combat.KBDisplacement;
import keystrokesmod.module.impl.combat.KillAura;
import keystrokesmod.module.impl.combat.KnockbackDelay;
import keystrokesmod.module.impl.combat.Piercing;
import keystrokesmod.module.impl.combat.RawInput;
import keystrokesmod.module.impl.combat.Reach;
import keystrokesmod.module.impl.combat.Reduce;
import keystrokesmod.module.impl.combat.RodAimbot;
import keystrokesmod.module.impl.combat.TPAura;
import keystrokesmod.module.impl.combat.Velocity;
import keystrokesmod.module.impl.combat.WTap;
import keystrokesmod.module.impl.fun.ExtraBobbing;
import keystrokesmod.module.impl.fun.FlameTrail;
import keystrokesmod.module.impl.fun.SlyPort;
import keystrokesmod.module.impl.fun.Spin;
import keystrokesmod.module.impl.minigames.AutoRequeue;
import keystrokesmod.module.impl.minigames.AutoWho;
import keystrokesmod.module.impl.minigames.BedWars;
import keystrokesmod.module.impl.minigames.BridgeInfo;
import keystrokesmod.module.impl.minigames.DuelsStats;
import keystrokesmod.module.impl.minigames.MurderMystery;
import keystrokesmod.module.impl.minigames.SkyWars;
import keystrokesmod.module.impl.minigames.SpeedBuilders;
import keystrokesmod.module.impl.minigames.SumoFences;
import keystrokesmod.module.impl.minigames.WoolWars;
import keystrokesmod.module.impl.movement.BHop;
import keystrokesmod.module.impl.movement.Boost;
import keystrokesmod.module.impl.movement.Dolphin;
import keystrokesmod.module.impl.movement.Fly;
import keystrokesmod.module.impl.movement.InstantStop;
import keystrokesmod.module.impl.movement.InvMove;
import keystrokesmod.module.impl.movement.KeepSprint;
import keystrokesmod.module.impl.movement.LongJump;
import keystrokesmod.module.impl.movement.MovementFix;
import keystrokesmod.module.impl.movement.NoSlow;
import keystrokesmod.module.impl.movement.NullMove;
import keystrokesmod.module.impl.movement.Speed;
import keystrokesmod.module.impl.movement.Sprint;
import keystrokesmod.module.impl.movement.Stasis;
import keystrokesmod.module.impl.movement.StopMotion;
import keystrokesmod.module.impl.movement.Teleport;
import keystrokesmod.module.impl.movement.Timer;
import keystrokesmod.module.impl.movement.VClip;
import keystrokesmod.module.impl.other.Anticheat;
import keystrokesmod.module.impl.other.ChatBypass;
import keystrokesmod.module.impl.other.FakeChat;
import keystrokesmod.module.impl.other.LatencyAlerts;
import keystrokesmod.module.impl.other.NameHider;
import keystrokesmod.module.impl.other.ViewPackets;
import keystrokesmod.module.impl.player.AntiAFK;
import keystrokesmod.module.impl.player.AntiFireball;
import keystrokesmod.module.impl.player.BedDefender;
import keystrokesmod.module.impl.player.MisAntiPlace;
import keystrokesmod.module.impl.player.AutoJump;
import keystrokesmod.module.impl.player.AutoShop;
import keystrokesmod.module.impl.player.AutoSwap;
import keystrokesmod.module.impl.player.AutoTool;
import keystrokesmod.module.impl.player.BedAura;
import keystrokesmod.module.impl.player.BlockIn;
import keystrokesmod.module.impl.player.BridgeAssist;
import keystrokesmod.module.impl.player.BlockLadder;
import keystrokesmod.module.impl.player.Clutch;
import keystrokesmod.module.impl.player.DelayRemover;
import keystrokesmod.module.impl.player.FastMine;
import keystrokesmod.module.impl.player.FastPlace;
import keystrokesmod.module.impl.player.Freecam;
import keystrokesmod.module.impl.player.GhostHand;
import keystrokesmod.module.impl.player.HideWindow;
import keystrokesmod.module.impl.player.Inventory;
import keystrokesmod.module.impl.player.NoFall;
import keystrokesmod.module.impl.player.NoRotate;
import keystrokesmod.module.impl.player.SafeWalk;
import keystrokesmod.module.impl.player.Scaffold;
import keystrokesmod.module.impl.player.WaterBucket;
import keystrokesmod.module.impl.network.FakeLag;
import keystrokesmod.module.impl.network.LagRange;
import keystrokesmod.module.impl.network.Blink;
import keystrokesmod.module.impl.render.AntiDebuff;
import keystrokesmod.module.impl.render.AntiShuffle;
import keystrokesmod.module.impl.render.Arrows;
import keystrokesmod.module.impl.render.BedESP;
import keystrokesmod.module.impl.render.BlockESP;
import keystrokesmod.module.impl.render.BlockOverlay;
import keystrokesmod.module.impl.render.BreakProgress;
import keystrokesmod.module.impl.render.Chams;
import keystrokesmod.module.impl.render.ChestESP;
import keystrokesmod.module.impl.render.DamageTags;
import keystrokesmod.module.impl.render.DamageTint;
import keystrokesmod.module.impl.render.ExtendCamera;
import keystrokesmod.module.impl.render.FallView;
import keystrokesmod.module.impl.render.Freelook;
import keystrokesmod.module.impl.render.HUD;
import keystrokesmod.module.impl.render.Notifications;
import keystrokesmod.module.impl.render.HitParticles;
import keystrokesmod.module.impl.render.Holdlook;
import keystrokesmod.module.impl.render.Indicators;
import keystrokesmod.module.impl.render.ItemESP;
import keystrokesmod.module.impl.render.ItemPhysics;
import keystrokesmod.module.impl.render.MobESP;
import keystrokesmod.module.impl.render.Nametags;
import keystrokesmod.module.impl.render.NoCameraClip;
import keystrokesmod.module.impl.render.NoHurtCam;
import keystrokesmod.module.impl.render.PlayerESP;
import keystrokesmod.module.impl.render.PotionHUD;
import keystrokesmod.module.impl.render.Radar;
import keystrokesmod.module.impl.render.Saturation;
import keystrokesmod.module.impl.render.TNTTimer;
import keystrokesmod.module.impl.render.TargetHUD;
import keystrokesmod.module.impl.render.Tracers;
import keystrokesmod.module.impl.render.Trajectories;
import keystrokesmod.module.impl.render.Xray;
import keystrokesmod.module.impl.world.AntiBot;
import keystrokesmod.module.impl.world.Weather;
import keystrokesmod.script.Manager;
import keystrokesmod.utility.font.RavenFontRenderer;

public class ModuleManager {
    public static List<Module> modules = new ArrayList<Module>();
    public static List<Module> organizedModules = Collections.synchronizedList(new ArrayList());
    private static final Map<String, Module> modulesByName = new HashMap<String, Module>();
    private static final Map<String, Module> modulesByNormalizedName = new HashMap<String, Module>();
    private static final Map<Class<?>, Module> modulesByClass = new HashMap();
    public static NameHider nameHider;
    public static FastPlace fastPlace;
    public static MurderMystery murderMystery;
    public static InvMove invmove;
    public static SkyWars skyWars;
    public static AntiFireball antiFireball;
    public static BedAura bedAura;
    public static BridgeAssist bridgeAssist;
    public static FastMine fastMine;
    public static Scaffold scaffold;
    public static AntiShuffle antiShuffle;
    public static MovementFix movementFix;
    public static CommandLine commandLine;
    public static LongJump longJump;
    public static AntiBot antiBot;
    public static NoSlow noSlow;
    public static KillAura killAura;
    public static AutoClicker autoClicker;
    public static Autoblock autoblock;
    public static HitSelect hitSelect;
    public static KnockbackDelay knockbackDelay;
    public static HitBox hitBox;
    public static Reach reach;
    public static NoRotate noRotate;
    public static BlockESP blockESP;
    public static BedESP bedESP;
    public static Blink blink;
    public static Chams chams;
    public static HUD hud;
    public static Notifications notifications;
    public static PotionHUD potionHUD;
    public static Timer timer;
    public static Fly fly;
    public static WTap wTap;
    public static BlockLadder blockLadder;
    public static Clutch clutch;
    public static Velocity velocity;
    public static AntiDebuff antiDebuff;
    public static TargetHUD targetHUD;
    public static NoFall noFall;
    public static PlayerESP playerESP;
    public static MobESP mobESP;
    public static Reduce reduce;
    public static SafeWalk safeWalk;
    public static KeepSprint keepSprint;
    public static Piercing piercing;
    public static GhostHand ghostHand;
    public static AntiKnockback antiKnockback;
    public static ExtendCamera extendCamera;
    public static Freelook freelook;
    public static Inventory inventory;
    public static NoCameraClip noCameraClip;
    public static BedWars bedwars;
    public static BHop bHop;
    public static NoHurtCam noHurtCam;
    public static AutoTool autoTool;
    public static AutoShop autoShop;
    public static AutoSwap autoSwap;
    public static Sprint sprint;
    public static Weather weather;
    public static ChatCommands chatCommands;
    public static BlockIn blockIn;
    public static Relationships relationships;
    public static HideWindow hideWindow;
    public static BedDefender bedDefender;
    public static MisAntiPlace misAntiPlace;
    public static KBDisplacement kbDisplacement;

    public void register() {
        chatCommands = new ChatCommands();
        this.addModule(chatCommands);
        commandLine = new CommandLine();
        this.addModule(commandLine);
        this.addModule(new Gui());
        this.addModule(new Settings());
        relationships = new Relationships();
        this.addModule(relationships);
        if (Raven.playerRelationsManager == null || Raven.playerRelationsManager.isActive()) {
            relationships.enable();
        }
        this.addModule(new AimAssist());
        antiKnockback = new AntiKnockback();
        this.addModule(antiKnockback);
        autoClicker = new AutoClicker();
        this.addModule(autoClicker);
        this.addModule(new AutoWeapon());
        autoblock = new Autoblock();
        this.addModule(autoblock);
        blockIn = new BlockIn();
        this.addModule(blockIn);
        this.addModule(new ClickAssist());
        this.addModule(new KBDisplacement());
        hitSelect = new HitSelect();
        this.addModule(hitSelect);
        hitBox = new HitBox();
        this.addModule(hitBox);
        this.addModule(new JumpReset());
        killAura = new KillAura();
        this.addModule(killAura);
        knockbackDelay = new KnockbackDelay();
        this.addModule(knockbackDelay);
        modules.add(new LagRange());
        piercing = new Piercing();
        this.addModule(piercing);
        ghostHand = new GhostHand();
        this.addModule(ghostHand);
        this.addModule(new RawInput());
        reach = new Reach();
        this.addModule(reach);
        reduce = new Reduce();
        this.addModule(reduce);
        this.addModule(new RodAimbot());
        this.addModule(new TPAura());
        velocity = new Velocity();
        this.addModule(velocity);
        wTap = new WTap();
        this.addModule(wTap);
        this.addModule(new ExtraBobbing());
        this.addModule(new FlameTrail());
        this.addModule(new SlyPort());
        this.addModule(new Spin());
        this.addModule(new AutoRequeue());
        this.addModule(new AutoWho());
        bedwars = new BedWars();
        this.addModule(bedwars);
        this.addModule(new BridgeInfo());
        this.addModule(new DuelsStats());
        murderMystery = new MurderMystery();
        this.addModule(murderMystery);
        skyWars = new SkyWars();
        this.addModule(skyWars);
        this.addModule(new SpeedBuilders());
        this.addModule(new SumoFences());
        this.addModule(new WoolWars());
        bHop = new BHop();
        this.addModule(bHop);
        movementFix = new MovementFix();
        this.addModule(movementFix);
        this.addModule(new Boost());
        this.addModule(new Dolphin());
        fly = new Fly();
        this.addModule(fly);
        invmove = new InvMove();
        this.addModule(invmove);
        keepSprint = new KeepSprint();
        this.addModule(keepSprint);
        longJump = new LongJump();
        this.addModule(longJump);
        noSlow = new NoSlow();
        this.addModule(noSlow);
        this.addModule(new NullMove());
        this.addModule(new Speed());
        sprint = new Sprint();
        this.addModule(sprint);
        this.addModule(new Stasis());
        this.addModule(new StopMotion());
        this.addModule(new InstantStop());
        this.addModule(new Teleport());
        timer = new Timer();
        this.addModule(timer);
        this.addModule(new VClip());
        this.addModule(new Anticheat());
        this.addModule(new ChatBypass());
        this.addModule(new FakeChat());
        this.addModule(new LatencyAlerts());
        nameHider = new NameHider();
        this.addModule(nameHider);
        this.addModule(new ViewPackets());
        this.addModule(new AntiAFK());
        antiFireball = new AntiFireball();
        this.addModule(antiFireball);
        this.addModule(new AutoJump());
        autoSwap = new AutoSwap();
        this.addModule(autoSwap);
        blockLadder = new BlockLadder();
        this.addModule(blockLadder);
        clutch = new Clutch();
        this.addModule(clutch);
        bridgeAssist = new BridgeAssist();
        this.addModule(bridgeAssist);
        bedDefender = new BedDefender();
        this.addModule(bedDefender);
        misAntiPlace = new MisAntiPlace();
        this.addModule(misAntiPlace);
        autoTool = new AutoTool();
        this.addModule(autoTool);
        autoShop = new AutoShop();
        this.addModule(autoShop);
        bedAura = new BedAura();
        this.addModule(bedAura);
        modules.add(new Blink());
        this.addModule(new DelayRemover());
        fastMine = new FastMine();
        this.addModule(fastMine);
        fastPlace = new FastPlace();
        this.addModule(fastPlace);
        this.addModule(new FakeLag());
        this.addModule(new Freecam());
        hideWindow = new HideWindow();
        this.addModule(hideWindow);
        inventory = new Inventory();
        this.addModule(inventory);
        noFall = new NoFall();
        this.addModule(noFall);
        noRotate = new NoRotate();
        this.addModule(noRotate);
        safeWalk = new SafeWalk();
        this.addModule(safeWalk);
        this.addModule(new WaterBucket());
        this.addModule(new keystrokesmod.utility.profile.Manager());
        antiDebuff = new AntiDebuff();
        this.addModule(antiDebuff);
        antiShuffle = new AntiShuffle();
        this.addModule(antiShuffle);
        this.addModule(new Arrows());
        bedESP = new BedESP();
        this.addModule(bedESP);
        blockESP = new BlockESP();
        this.addModule(blockESP);
        this.addModule(new BlockOverlay());
        this.addModule(new BreakProgress());
        chams = new Chams();
        this.addModule(chams);
        this.addModule(new DamageTint());
        this.addModule(new DamageTags());
        this.addModule(new HitParticles());
        this.addModule(new ChestESP());
        extendCamera = new ExtendCamera();
        this.addModule(extendCamera);
        freelook = new Freelook();
        this.addModule(freelook);
        this.addModule(new FallView());
        this.addModule(new Holdlook());
        hud = new HUD();
        this.addModule(hud);
        notifications = new Notifications();
        this.addModule(notifications);
        this.addModule(new Indicators());
        this.addModule(new ItemESP());
        this.addModule(new ItemPhysics());
        mobESP = new MobESP();
        this.addModule(mobESP);
        this.addModule(new Nametags());
        noCameraClip = new NoCameraClip();
        this.addModule(noCameraClip);
        noHurtCam = new NoHurtCam();
        this.addModule(noHurtCam);
        playerESP = new PlayerESP();
        this.addModule(playerESP);
        potionHUD = new PotionHUD();
        this.addModule(potionHUD);
        this.addModule(new Radar());
        this.addModule(new Saturation());
        targetHUD = new TargetHUD();
        this.addModule(targetHUD);
        this.addModule(new Trajectories());
        this.addModule(new TNTTimer());
        this.addModule(new Tracers());
        this.addModule(new Xray());
        scaffold = new Scaffold();
        this.addModule(scaffold);
        antiBot = new AntiBot();
        this.addModule(antiBot);
        weather = new Weather();
        this.addModule(weather);
        this.addModule(new Manager());
        movementFix.enable();
        antiBot.enable();
        modules.sort(Comparator.comparing(Module::getName));
    }

    public void addModule(Module module) {
        modules.add(module);
        modulesByName.put(module.getName(), module);
        modulesByNormalizedName.put(ModuleManager.normalizeModuleName(module.getName()), module);
        modulesByClass.put(module.getClass(), module);
    }

    public List<Module> getModules() {
        return modules;
    }

    public List<Module> inCategory(Module.category category2) {
        ArrayList<Module> categoryModules = new ArrayList<Module>();
        for (Module module : this.getModules()) {
            if (!module.moduleCategory().equals((Object)category2)) continue;
            categoryModules.add(module);
        }
        return categoryModules;
    }

    public static Module getModule(String moduleName) {
        Module module = modulesByName.get(moduleName);
        if (module != null) {
            return module;
        }
        return modulesByNormalizedName.get(ModuleManager.normalizeModuleName(moduleName));
    }

    public static Module getModule(Class<?> clazz) {
        return modulesByClass.get(clazz);
    }

    public static void sort() {
        if (HUD.alphabeticalSort.isToggled()) {
            organizedModules.sort(Comparator.comparing(Module::getNameInHud));
            return;
        }
        RavenFontRenderer hudFont = HUD.getHudFontRenderer();
        organizedModules.sort((o1, o2) -> hudFont.getStringWidth(HUD.getHudRenderText(o2)) - hudFont.getStringWidth(HUD.getHudRenderText(o1)));
    }

    private static String normalizeModuleName(String moduleName) {
        if (moduleName == null) {
            return "";
        }
        StringBuilder normalized = new StringBuilder(moduleName.length());
        for (int i = 0; i < moduleName.length(); ++i) {
            char character = moduleName.charAt(i);
            if (!Character.isLetterOrDigit(character)) continue;
            normalized.append(Character.toLowerCase(character));
        }
        return normalized.toString();
    }
}

